// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BrokenLinksInitParameters struct {

	// (Set of String) If your application relies on other hosts at other domains, add the associated domain names here. Once configured, Dynatrace will consider 404s thrown by hosts at these domains to be service failures related to your application.
	// If your application relies on other hosts at other domains, add the associated domain names here. Once configured, Dynatrace will consider 404s thrown by hosts at these domains to be service failures related to your application.
	// +listType=set
	BrokenLinkDomains []*string `json:"brokenLinkDomains,omitempty" tf:"broken_link_domains,omitempty"`

	// (Boolean) Consider 404 HTTP response codes as failures
	// Consider 404 HTTP response codes as failures
	HTTP404NotFoundFailures *bool `json:"http404NotFoundFailures,omitempty" tf:"http_404_not_found_failures,omitempty"`
}

type BrokenLinksObservation struct {

	// (Set of String) If your application relies on other hosts at other domains, add the associated domain names here. Once configured, Dynatrace will consider 404s thrown by hosts at these domains to be service failures related to your application.
	// If your application relies on other hosts at other domains, add the associated domain names here. Once configured, Dynatrace will consider 404s thrown by hosts at these domains to be service failures related to your application.
	// +listType=set
	BrokenLinkDomains []*string `json:"brokenLinkDomains,omitempty" tf:"broken_link_domains,omitempty"`

	// (Boolean) Consider 404 HTTP response codes as failures
	// Consider 404 HTTP response codes as failures
	HTTP404NotFoundFailures *bool `json:"http404NotFoundFailures,omitempty" tf:"http_404_not_found_failures,omitempty"`
}

type BrokenLinksParameters struct {

	// (Set of String) If your application relies on other hosts at other domains, add the associated domain names here. Once configured, Dynatrace will consider 404s thrown by hosts at these domains to be service failures related to your application.
	// If your application relies on other hosts at other domains, add the associated domain names here. Once configured, Dynatrace will consider 404s thrown by hosts at these domains to be service failures related to your application.
	// +kubebuilder:validation:Optional
	// +listType=set
	BrokenLinkDomains []*string `json:"brokenLinkDomains,omitempty" tf:"broken_link_domains,omitempty"`

	// (Boolean) Consider 404 HTTP response codes as failures
	// Consider 404 HTTP response codes as failures
	// +kubebuilder:validation:Optional
	HTTP404NotFoundFailures *bool `json:"http404NotFoundFailures" tf:"http_404_not_found_failures,omitempty"`
}

type HTTPFailureInitParameters struct {

	// side service failures. (see below for nested schema)
	// HTTP 404 response codes are thrown when a web server can't find a certain page. 404s are classified as broken links on the client side and therefore aren't considered to be service failures. By enabling this setting, you can have 404s treated as server-side service failures.
	BrokenLinks []BrokenLinksInitParameters `json:"brokenLinks,omitempty" tf:"broken_links,omitempty"`

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Block List, Max: 1) HTTP response codes (see below for nested schema)
	// HTTP response codes
	HTTPResponseCodes []HTTPResponseCodesInitParameters `json:"httpResponseCodes,omitempty" tf:"http_response_codes,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`
}

type HTTPFailureObservation struct {

	// side service failures. (see below for nested schema)
	// HTTP 404 response codes are thrown when a web server can't find a certain page. 404s are classified as broken links on the client side and therefore aren't considered to be service failures. By enabling this setting, you can have 404s treated as server-side service failures.
	BrokenLinks []BrokenLinksObservation `json:"brokenLinks,omitempty" tf:"broken_links,omitempty"`

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Block List, Max: 1) HTTP response codes (see below for nested schema)
	// HTTP response codes
	HTTPResponseCodes []HTTPResponseCodesObservation `json:"httpResponseCodes,omitempty" tf:"http_response_codes,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`
}

type HTTPFailureParameters struct {

	// side service failures. (see below for nested schema)
	// HTTP 404 response codes are thrown when a web server can't find a certain page. 404s are classified as broken links on the client side and therefore aren't considered to be service failures. By enabling this setting, you can have 404s treated as server-side service failures.
	// +kubebuilder:validation:Optional
	BrokenLinks []BrokenLinksParameters `json:"brokenLinks,omitempty" tf:"broken_links,omitempty"`

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Block List, Max: 1) HTTP response codes (see below for nested schema)
	// HTTP response codes
	// +kubebuilder:validation:Optional
	HTTPResponseCodes []HTTPResponseCodesParameters `json:"httpResponseCodes,omitempty" tf:"http_response_codes,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// +kubebuilder:validation:Optional
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`
}

type HTTPResponseCodesInitParameters struct {

	// (String) HTTP response codes which indicate client side errors
	// HTTP response codes which indicate client side errors
	ClientSideErrors *string `json:"clientSideErrors,omitempty" tf:"client_side_errors,omitempty"`

	// (Boolean) Treat missing HTTP response code as client side error
	// Treat missing HTTP response code as client side error
	FailOnMissingResponseCodeClientSide *bool `json:"failOnMissingResponseCodeClientSide,omitempty" tf:"fail_on_missing_response_code_client_side,omitempty"`

	// (Boolean) Treat missing HTTP response code as server side errors
	// Treat missing HTTP response code as server side errors
	FailOnMissingResponseCodeServerSide *bool `json:"failOnMissingResponseCodeServerSide,omitempty" tf:"fail_on_missing_response_code_server_side,omitempty"`

	// (String) HTTP response codes which indicate an error on the server side
	// HTTP response codes which indicate an error on the server side
	ServerSideErrors *string `json:"serverSideErrors,omitempty" tf:"server_side_errors,omitempty"`
}

type HTTPResponseCodesObservation struct {

	// (String) HTTP response codes which indicate client side errors
	// HTTP response codes which indicate client side errors
	ClientSideErrors *string `json:"clientSideErrors,omitempty" tf:"client_side_errors,omitempty"`

	// (Boolean) Treat missing HTTP response code as client side error
	// Treat missing HTTP response code as client side error
	FailOnMissingResponseCodeClientSide *bool `json:"failOnMissingResponseCodeClientSide,omitempty" tf:"fail_on_missing_response_code_client_side,omitempty"`

	// (Boolean) Treat missing HTTP response code as server side errors
	// Treat missing HTTP response code as server side errors
	FailOnMissingResponseCodeServerSide *bool `json:"failOnMissingResponseCodeServerSide,omitempty" tf:"fail_on_missing_response_code_server_side,omitempty"`

	// (String) HTTP response codes which indicate an error on the server side
	// HTTP response codes which indicate an error on the server side
	ServerSideErrors *string `json:"serverSideErrors,omitempty" tf:"server_side_errors,omitempty"`
}

type HTTPResponseCodesParameters struct {

	// (String) HTTP response codes which indicate client side errors
	// HTTP response codes which indicate client side errors
	// +kubebuilder:validation:Optional
	ClientSideErrors *string `json:"clientSideErrors" tf:"client_side_errors,omitempty"`

	// (Boolean) Treat missing HTTP response code as client side error
	// Treat missing HTTP response code as client side error
	// +kubebuilder:validation:Optional
	FailOnMissingResponseCodeClientSide *bool `json:"failOnMissingResponseCodeClientSide" tf:"fail_on_missing_response_code_client_side,omitempty"`

	// (Boolean) Treat missing HTTP response code as server side errors
	// Treat missing HTTP response code as server side errors
	// +kubebuilder:validation:Optional
	FailOnMissingResponseCodeServerSide *bool `json:"failOnMissingResponseCodeServerSide" tf:"fail_on_missing_response_code_server_side,omitempty"`

	// (String) HTTP response codes which indicate an error on the server side
	// HTTP response codes which indicate an error on the server side
	// +kubebuilder:validation:Optional
	ServerSideErrors *string `json:"serverSideErrors" tf:"server_side_errors,omitempty"`
}

// HTTPFailureSpec defines the desired state of HTTPFailure
type HTTPFailureSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HTTPFailureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HTTPFailureInitParameters `json:"initProvider,omitempty"`
}

// HTTPFailureStatus defines the observed state of HTTPFailure.
type HTTPFailureStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HTTPFailureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// HTTPFailure is the Schema for the HTTPFailures API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,dynatrace}
type HTTPFailure struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceId) || (has(self.initProvider) && has(self.initProvider.serviceId))",message="spec.forProvider.serviceId is a required parameter"
	Spec   HTTPFailureSpec   `json:"spec"`
	Status HTTPFailureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HTTPFailureList contains a list of HTTPFailures
type HTTPFailureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HTTPFailure `json:"items"`
}

// Repository type metadata.
var (
	HTTPFailure_Kind             = "HTTPFailure"
	HTTPFailure_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: HTTPFailure_Kind}.String()
	HTTPFailure_KindAPIVersion   = HTTPFailure_Kind + "." + CRDGroupVersion.String()
	HTTPFailure_GroupVersionKind = CRDGroupVersion.WithKind(HTTPFailure_Kind)
)

func init() {
	SchemeBuilder.Register(&HTTPFailure{}, &HTTPFailureList{})
}
