// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DevelopmentEnvironmentsInitParameters struct {

	// company.my-cde-provider.com.
	// The URL to allow app development from. E.g. `https://*.my-company.my-cde-provider.com`.
	// +listType=set
	CloudDevelopmentEnvironments []*string `json:"cloudDevelopmentEnvironments,omitempty" tf:"cloud_development_environments,omitempty"`
}

type DevelopmentEnvironmentsObservation struct {

	// company.my-cde-provider.com.
	// The URL to allow app development from. E.g. `https://*.my-company.my-cde-provider.com`.
	// +listType=set
	CloudDevelopmentEnvironments []*string `json:"cloudDevelopmentEnvironments,omitempty" tf:"cloud_development_environments,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DevelopmentEnvironmentsParameters struct {

	// company.my-cde-provider.com.
	// The URL to allow app development from. E.g. `https://*.my-company.my-cde-provider.com`.
	// +kubebuilder:validation:Optional
	// +listType=set
	CloudDevelopmentEnvironments []*string `json:"cloudDevelopmentEnvironments,omitempty" tf:"cloud_development_environments,omitempty"`
}

// DevelopmentEnvironmentsSpec defines the desired state of DevelopmentEnvironments
type DevelopmentEnvironmentsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DevelopmentEnvironmentsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DevelopmentEnvironmentsInitParameters `json:"initProvider,omitempty"`
}

// DevelopmentEnvironmentsStatus defines the observed state of DevelopmentEnvironments.
type DevelopmentEnvironmentsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DevelopmentEnvironmentsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DevelopmentEnvironments is the Schema for the DevelopmentEnvironmentss API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type DevelopmentEnvironments struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DevelopmentEnvironmentsSpec   `json:"spec"`
	Status            DevelopmentEnvironmentsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DevelopmentEnvironmentsList contains a list of DevelopmentEnvironmentss
type DevelopmentEnvironmentsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DevelopmentEnvironments `json:"items"`
}

// Repository type metadata.
var (
	DevelopmentEnvironments_Kind             = "DevelopmentEnvironments"
	DevelopmentEnvironments_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DevelopmentEnvironments_Kind}.String()
	DevelopmentEnvironments_KindAPIVersion   = DevelopmentEnvironments_Kind + "." + CRDGroupVersion.String()
	DevelopmentEnvironments_GroupVersionKind = CRDGroupVersion.WithKind(DevelopmentEnvironments_Kind)
)

func init() {
	SchemeBuilder.Register(&DevelopmentEnvironments{}, &DevelopmentEnvironmentsList{})
}
