// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ConnectionRoleArnInitParameters struct {

	// (String) The ID of a dynatrace_aws_connection resource instance for which to define the AWS Role ARN
	// The ID of a `dynatrace_aws_connection` resource instance for which to define the AWS Role ARN
	AwsConnectionID *string `json:"awsConnectionId,omitempty" tf:"aws_connection_id,omitempty"`

	// (String) The ARN of the AWS role that should be assumed.
	// The ARN of the AWS role that should be assumed.
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`
}

type ConnectionRoleArnObservation struct {

	// (String) The ID of a dynatrace_aws_connection resource instance for which to define the AWS Role ARN
	// The ID of a `dynatrace_aws_connection` resource instance for which to define the AWS Role ARN
	AwsConnectionID *string `json:"awsConnectionId,omitempty" tf:"aws_connection_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ARN of the AWS role that should be assumed.
	// The ARN of the AWS role that should be assumed.
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`
}

type ConnectionRoleArnParameters struct {

	// (String) The ID of a dynatrace_aws_connection resource instance for which to define the AWS Role ARN
	// The ID of a `dynatrace_aws_connection` resource instance for which to define the AWS Role ARN
	// +kubebuilder:validation:Optional
	AwsConnectionID *string `json:"awsConnectionId,omitempty" tf:"aws_connection_id,omitempty"`

	// (String) The ARN of the AWS role that should be assumed.
	// The ARN of the AWS role that should be assumed.
	// +kubebuilder:validation:Optional
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`
}

// ConnectionRoleArnSpec defines the desired state of ConnectionRoleArn
type ConnectionRoleArnSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConnectionRoleArnParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectionRoleArnInitParameters `json:"initProvider,omitempty"`
}

// ConnectionRoleArnStatus defines the observed state of ConnectionRoleArn.
type ConnectionRoleArnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConnectionRoleArnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConnectionRoleArn is the Schema for the ConnectionRoleArns API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,dynatrace}
type ConnectionRoleArn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.awsConnectionId) || (has(self.initProvider) && has(self.initProvider.awsConnectionId))",message="spec.forProvider.awsConnectionId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleArn) || (has(self.initProvider) && has(self.initProvider.roleArn))",message="spec.forProvider.roleArn is a required parameter"
	Spec   ConnectionRoleArnSpec   `json:"spec"`
	Status ConnectionRoleArnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectionRoleArnList contains a list of ConnectionRoleArns
type ConnectionRoleArnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectionRoleArn `json:"items"`
}

// Repository type metadata.
var (
	ConnectionRoleArn_Kind             = "ConnectionRoleArn"
	ConnectionRoleArn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConnectionRoleArn_Kind}.String()
	ConnectionRoleArn_KindAPIVersion   = ConnectionRoleArn_Kind + "." + CRDGroupVersion.String()
	ConnectionRoleArn_GroupVersionKind = CRDGroupVersion.WithKind(ConnectionRoleArn_Kind)
)

func init() {
	SchemeBuilder.Register(&ConnectionRoleArn{}, &ConnectionRoleArnList{})
}
