// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type V2UsersessionsPipelinegroupsCompositionInitParameters struct {

	// (Block List, Min: 1) (see below for nested schema)
	PipelineGroupComposition []V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionInitParameters `json:"pipelineGroupComposition,omitempty" tf:"pipeline_group_composition,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionObservation struct {

	// (Block List, Min: 1) (see below for nested schema)
	PipelineGroupComposition []V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionObservation `json:"pipelineGroupComposition,omitempty" tf:"pipeline_group_composition,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionParameters struct {

	// (Block List, Min: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	PipelineGroupComposition []V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionParameters `json:"pipelineGroupComposition" tf:"pipeline_group_composition,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionInitParameters struct {

	// (Boolean) Placeholder for the wrapped pipeline
	// Placeholder for the wrapped pipeline
	IsPipelinePlaceholder *bool `json:"isPipelinePlaceholder,omitempty" tf:"is_pipeline_placeholder,omitempty"`

	// (String) Pipeline ID
	// Pipeline ID
	PipelineID *string `json:"pipelineId,omitempty" tf:"pipeline_id,omitempty"`

	// (Block List, Max: 1) stage configuration for this pipelines (see below for nested schema)
	// stage configuration for this pipelines
	Stages []V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionStagesInitParameters `json:"stages,omitempty" tf:"stages,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionObservation struct {

	// (Boolean) Placeholder for the wrapped pipeline
	// Placeholder for the wrapped pipeline
	IsPipelinePlaceholder *bool `json:"isPipelinePlaceholder,omitempty" tf:"is_pipeline_placeholder,omitempty"`

	// (String) Pipeline ID
	// Pipeline ID
	PipelineID *string `json:"pipelineId,omitempty" tf:"pipeline_id,omitempty"`

	// (Block List, Max: 1) stage configuration for this pipelines (see below for nested schema)
	// stage configuration for this pipelines
	Stages []V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionStagesObservation `json:"stages,omitempty" tf:"stages,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionParameters struct {

	// (Boolean) Placeholder for the wrapped pipeline
	// Placeholder for the wrapped pipeline
	// +kubebuilder:validation:Optional
	IsPipelinePlaceholder *bool `json:"isPipelinePlaceholder" tf:"is_pipeline_placeholder,omitempty"`

	// (String) Pipeline ID
	// Pipeline ID
	// +kubebuilder:validation:Optional
	PipelineID *string `json:"pipelineId,omitempty" tf:"pipeline_id,omitempty"`

	// (Block List, Max: 1) stage configuration for this pipelines (see below for nested schema)
	// stage configuration for this pipelines
	// +kubebuilder:validation:Optional
	Stages []V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionStagesParameters `json:"stages,omitempty" tf:"stages,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionStagesInitParameters struct {

	// (Set of String) exclude stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// exclude stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Set of String) include stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// include stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`

	// (String) Stage configuration type. Possible values: exclude, include, includeAll
	// Stage configuration type. Possible values: `exclude`, `include`, `includeAll`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionStagesObservation struct {

	// (Set of String) exclude stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// exclude stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Set of String) include stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// include stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`

	// (String) Stage configuration type. Possible values: exclude, include, includeAll
	// Stage configuration type. Possible values: `exclude`, `include`, `includeAll`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type V2UsersessionsPipelinegroupsCompositionPipelineGroupCompositionStagesParameters struct {

	// (Set of String) exclude stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// exclude stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +kubebuilder:validation:Optional
	// +listType=set
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Set of String) include stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// include stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +kubebuilder:validation:Optional
	// +listType=set
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`

	// (String) Stage configuration type. Possible values: exclude, include, includeAll
	// Stage configuration type. Possible values: `exclude`, `include`, `includeAll`
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type V2UsersessionsPipelinegroupsInitParameters struct {

	// (Block List, Max: 1) Composition (see below for nested schema)
	// Composition
	Composition []V2UsersessionsPipelinegroupsCompositionInitParameters `json:"composition,omitempty" tf:"composition,omitempty"`

	// (String) Display name
	// Display name
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Set of String) Pipelines wrapped by this group
	// Pipelines wrapped by this group
	// +listType=set
	MemberPipelines []*string `json:"memberPipelines,omitempty" tf:"member_pipelines,omitempty"`

	// (Block List, Min: 1, Max: 1) stage configuration of the member pipelines (see below for nested schema)
	// stage configuration of the member pipelines
	MemberStages []V2UsersessionsPipelinegroupsMemberStagesInitParameters `json:"memberStages,omitempty" tf:"member_stages,omitempty"`
}

type V2UsersessionsPipelinegroupsMemberStagesInitParameters struct {

	// (Set of String) exclude stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// exclude stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Set of String) include stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// include stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`

	// (String) Stage configuration type. Possible values: exclude, include, includeAll
	// Stage configuration type. Possible values: `exclude`, `include`, `includeAll`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type V2UsersessionsPipelinegroupsMemberStagesObservation struct {

	// (Set of String) exclude stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// exclude stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Set of String) include stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// include stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +listType=set
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`

	// (String) Stage configuration type. Possible values: exclude, include, includeAll
	// Stage configuration type. Possible values: `exclude`, `include`, `includeAll`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type V2UsersessionsPipelinegroupsMemberStagesParameters struct {

	// (Set of String) exclude stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// exclude stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +kubebuilder:validation:Optional
	// +listType=set
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Set of String) include stages. Possible values: costAllocation, dataExtraction, davis, metricExtraction, processing, productAllocation, securityContext, smartscapeEdgeExtraction, smartscapeNodeExtraction, storage
	// include stages. Possible values: `costAllocation`, `dataExtraction`, `davis`, `metricExtraction`, `processing`, `productAllocation`, `securityContext`, `smartscapeEdgeExtraction`, `smartscapeNodeExtraction`, `storage`
	// +kubebuilder:validation:Optional
	// +listType=set
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`

	// (String) Stage configuration type. Possible values: exclude, include, includeAll
	// Stage configuration type. Possible values: `exclude`, `include`, `includeAll`
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type V2UsersessionsPipelinegroupsObservation struct {

	// (Block List, Max: 1) Composition (see below for nested schema)
	// Composition
	Composition []V2UsersessionsPipelinegroupsCompositionObservation `json:"composition,omitempty" tf:"composition,omitempty"`

	// (String) Display name
	// Display name
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) Pipelines wrapped by this group
	// Pipelines wrapped by this group
	// +listType=set
	MemberPipelines []*string `json:"memberPipelines,omitempty" tf:"member_pipelines,omitempty"`

	// (Block List, Min: 1, Max: 1) stage configuration of the member pipelines (see below for nested schema)
	// stage configuration of the member pipelines
	MemberStages []V2UsersessionsPipelinegroupsMemberStagesObservation `json:"memberStages,omitempty" tf:"member_stages,omitempty"`
}

type V2UsersessionsPipelinegroupsParameters struct {

	// (Block List, Max: 1) Composition (see below for nested schema)
	// Composition
	// +kubebuilder:validation:Optional
	Composition []V2UsersessionsPipelinegroupsCompositionParameters `json:"composition,omitempty" tf:"composition,omitempty"`

	// (String) Display name
	// Display name
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Set of String) Pipelines wrapped by this group
	// Pipelines wrapped by this group
	// +kubebuilder:validation:Optional
	// +listType=set
	MemberPipelines []*string `json:"memberPipelines,omitempty" tf:"member_pipelines,omitempty"`

	// (Block List, Min: 1, Max: 1) stage configuration of the member pipelines (see below for nested schema)
	// stage configuration of the member pipelines
	// +kubebuilder:validation:Optional
	MemberStages []V2UsersessionsPipelinegroupsMemberStagesParameters `json:"memberStages,omitempty" tf:"member_stages,omitempty"`
}

// V2UsersessionsPipelinegroupsSpec defines the desired state of V2UsersessionsPipelinegroups
type V2UsersessionsPipelinegroupsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     V2UsersessionsPipelinegroupsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider V2UsersessionsPipelinegroupsInitParameters `json:"initProvider,omitempty"`
}

// V2UsersessionsPipelinegroupsStatus defines the observed state of V2UsersessionsPipelinegroups.
type V2UsersessionsPipelinegroupsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        V2UsersessionsPipelinegroupsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// V2UsersessionsPipelinegroups is the Schema for the V2UsersessionsPipelinegroupss API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type V2UsersessionsPipelinegroups struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.memberStages) || (has(self.initProvider) && has(self.initProvider.memberStages))",message="spec.forProvider.memberStages is a required parameter"
	Spec   V2UsersessionsPipelinegroupsSpec   `json:"spec"`
	Status V2UsersessionsPipelinegroupsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// V2UsersessionsPipelinegroupsList contains a list of V2UsersessionsPipelinegroupss
type V2UsersessionsPipelinegroupsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []V2UsersessionsPipelinegroups `json:"items"`
}

// Repository type metadata.
var (
	V2UsersessionsPipelinegroups_Kind             = "V2UsersessionsPipelinegroups"
	V2UsersessionsPipelinegroups_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: V2UsersessionsPipelinegroups_Kind}.String()
	V2UsersessionsPipelinegroups_KindAPIVersion   = V2UsersessionsPipelinegroups_Kind + "." + CRDGroupVersion.String()
	V2UsersessionsPipelinegroups_GroupVersionKind = CRDGroupVersion.WithKind(V2UsersessionsPipelinegroups_Kind)
)

func init() {
	SchemeBuilder.Register(&V2UsersessionsPipelinegroups{}, &V2UsersessionsPipelinegroupsList{})
}
