//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allowlist) DeepCopyInto(out *Allowlist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allowlist.
func (in *Allowlist) DeepCopy() *Allowlist {
	if in == nil {
		return nil
	}
	out := new(Allowlist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Allowlist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistAllowlistInitParameters) DeepCopyInto(out *AllowlistAllowlistInitParameters) {
	*out = *in
	if in.Urlpattern != nil {
		in, out := &in.Urlpattern, &out.Urlpattern
		*out = make([]UrlpatternInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistAllowlistInitParameters.
func (in *AllowlistAllowlistInitParameters) DeepCopy() *AllowlistAllowlistInitParameters {
	if in == nil {
		return nil
	}
	out := new(AllowlistAllowlistInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistAllowlistObservation) DeepCopyInto(out *AllowlistAllowlistObservation) {
	*out = *in
	if in.Urlpattern != nil {
		in, out := &in.Urlpattern, &out.Urlpattern
		*out = make([]UrlpatternObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistAllowlistObservation.
func (in *AllowlistAllowlistObservation) DeepCopy() *AllowlistAllowlistObservation {
	if in == nil {
		return nil
	}
	out := new(AllowlistAllowlistObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistAllowlistParameters) DeepCopyInto(out *AllowlistAllowlistParameters) {
	*out = *in
	if in.Urlpattern != nil {
		in, out := &in.Urlpattern, &out.Urlpattern
		*out = make([]UrlpatternParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistAllowlistParameters.
func (in *AllowlistAllowlistParameters) DeepCopy() *AllowlistAllowlistParameters {
	if in == nil {
		return nil
	}
	out := new(AllowlistAllowlistParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistInitParameters) DeepCopyInto(out *AllowlistInitParameters) {
	*out = *in
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make([]AllowlistAllowlistInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistInitParameters.
func (in *AllowlistInitParameters) DeepCopy() *AllowlistInitParameters {
	if in == nil {
		return nil
	}
	out := new(AllowlistInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistList) DeepCopyInto(out *AllowlistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Allowlist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistList.
func (in *AllowlistList) DeepCopy() *AllowlistList {
	if in == nil {
		return nil
	}
	out := new(AllowlistList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AllowlistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistObservation) DeepCopyInto(out *AllowlistObservation) {
	*out = *in
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make([]AllowlistAllowlistObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistObservation.
func (in *AllowlistObservation) DeepCopy() *AllowlistObservation {
	if in == nil {
		return nil
	}
	out := new(AllowlistObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistParameters) DeepCopyInto(out *AllowlistParameters) {
	*out = *in
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make([]AllowlistAllowlistParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistParameters.
func (in *AllowlistParameters) DeepCopy() *AllowlistParameters {
	if in == nil {
		return nil
	}
	out := new(AllowlistParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistSpec) DeepCopyInto(out *AllowlistSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistSpec.
func (in *AllowlistSpec) DeepCopy() *AllowlistSpec {
	if in == nil {
		return nil
	}
	out := new(AllowlistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowlistStatus) DeepCopyInto(out *AllowlistStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowlistStatus.
func (in *AllowlistStatus) DeepCopy() *AllowlistStatus {
	if in == nil {
		return nil
	}
	out := new(AllowlistStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPresetsInitParameters) DeepCopyInto(out *DashboardPresetsInitParameters) {
	*out = *in
	if in.DashboardPreset != nil {
		in, out := &in.DashboardPreset, &out.DashboardPreset
		*out = new(string)
		**out = **in
	}
	if in.UserGroup != nil {
		in, out := &in.UserGroup, &out.UserGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPresetsInitParameters.
func (in *DashboardPresetsInitParameters) DeepCopy() *DashboardPresetsInitParameters {
	if in == nil {
		return nil
	}
	out := new(DashboardPresetsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPresetsListInitParameters) DeepCopyInto(out *DashboardPresetsListInitParameters) {
	*out = *in
	if in.DashboardPresets != nil {
		in, out := &in.DashboardPresets, &out.DashboardPresets
		*out = make([]DashboardPresetsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPresetsListInitParameters.
func (in *DashboardPresetsListInitParameters) DeepCopy() *DashboardPresetsListInitParameters {
	if in == nil {
		return nil
	}
	out := new(DashboardPresetsListInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPresetsListObservation) DeepCopyInto(out *DashboardPresetsListObservation) {
	*out = *in
	if in.DashboardPresets != nil {
		in, out := &in.DashboardPresets, &out.DashboardPresets
		*out = make([]DashboardPresetsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPresetsListObservation.
func (in *DashboardPresetsListObservation) DeepCopy() *DashboardPresetsListObservation {
	if in == nil {
		return nil
	}
	out := new(DashboardPresetsListObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPresetsListParameters) DeepCopyInto(out *DashboardPresetsListParameters) {
	*out = *in
	if in.DashboardPresets != nil {
		in, out := &in.DashboardPresets, &out.DashboardPresets
		*out = make([]DashboardPresetsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPresetsListParameters.
func (in *DashboardPresetsListParameters) DeepCopy() *DashboardPresetsListParameters {
	if in == nil {
		return nil
	}
	out := new(DashboardPresetsListParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPresetsObservation) DeepCopyInto(out *DashboardPresetsObservation) {
	*out = *in
	if in.DashboardPreset != nil {
		in, out := &in.DashboardPreset, &out.DashboardPreset
		*out = new(string)
		**out = **in
	}
	if in.UserGroup != nil {
		in, out := &in.UserGroup, &out.UserGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPresetsObservation.
func (in *DashboardPresetsObservation) DeepCopy() *DashboardPresetsObservation {
	if in == nil {
		return nil
	}
	out := new(DashboardPresetsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPresetsParameters) DeepCopyInto(out *DashboardPresetsParameters) {
	*out = *in
	if in.DashboardPreset != nil {
		in, out := &in.DashboardPreset, &out.DashboardPreset
		*out = new(string)
		**out = **in
	}
	if in.UserGroup != nil {
		in, out := &in.UserGroup, &out.UserGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPresetsParameters.
func (in *DashboardPresetsParameters) DeepCopy() *DashboardPresetsParameters {
	if in == nil {
		return nil
	}
	out := new(DashboardPresetsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDashboardInitParameters) DeepCopyInto(out *DefaultDashboardInitParameters) {
	*out = *in
	if in.Dashboard != nil {
		in, out := &in.Dashboard, &out.Dashboard
		*out = new(string)
		**out = **in
	}
	if in.UserGroup != nil {
		in, out := &in.UserGroup, &out.UserGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDashboardInitParameters.
func (in *DefaultDashboardInitParameters) DeepCopy() *DefaultDashboardInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDashboardInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDashboardListInitParameters) DeepCopyInto(out *DefaultDashboardListInitParameters) {
	*out = *in
	if in.DefaultDashboard != nil {
		in, out := &in.DefaultDashboard, &out.DefaultDashboard
		*out = make([]DefaultDashboardInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDashboardListInitParameters.
func (in *DefaultDashboardListInitParameters) DeepCopy() *DefaultDashboardListInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDashboardListInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDashboardListObservation) DeepCopyInto(out *DefaultDashboardListObservation) {
	*out = *in
	if in.DefaultDashboard != nil {
		in, out := &in.DefaultDashboard, &out.DefaultDashboard
		*out = make([]DefaultDashboardObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDashboardListObservation.
func (in *DefaultDashboardListObservation) DeepCopy() *DefaultDashboardListObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultDashboardListObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDashboardListParameters) DeepCopyInto(out *DefaultDashboardListParameters) {
	*out = *in
	if in.DefaultDashboard != nil {
		in, out := &in.DefaultDashboard, &out.DefaultDashboard
		*out = make([]DefaultDashboardParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDashboardListParameters.
func (in *DefaultDashboardListParameters) DeepCopy() *DefaultDashboardListParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDashboardListParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDashboardObservation) DeepCopyInto(out *DefaultDashboardObservation) {
	*out = *in
	if in.Dashboard != nil {
		in, out := &in.Dashboard, &out.Dashboard
		*out = new(string)
		**out = **in
	}
	if in.UserGroup != nil {
		in, out := &in.UserGroup, &out.UserGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDashboardObservation.
func (in *DefaultDashboardObservation) DeepCopy() *DefaultDashboardObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultDashboardObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDashboardParameters) DeepCopyInto(out *DefaultDashboardParameters) {
	*out = *in
	if in.Dashboard != nil {
		in, out := &in.Dashboard, &out.Dashboard
		*out = new(string)
		**out = **in
	}
	if in.UserGroup != nil {
		in, out := &in.UserGroup, &out.UserGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDashboardParameters.
func (in *DefaultDashboardParameters) DeepCopy() *DefaultDashboardParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDashboardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *General) DeepCopyInto(out *General) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new General.
func (in *General) DeepCopy() *General {
	if in == nil {
		return nil
	}
	out := new(General)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *General) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralInitParameters) DeepCopyInto(out *GeneralInitParameters) {
	*out = *in
	if in.DefaultDashboardList != nil {
		in, out := &in.DefaultDashboardList, &out.DefaultDashboardList
		*out = make([]DefaultDashboardListInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnablePublicSharing != nil {
		in, out := &in.EnablePublicSharing, &out.EnablePublicSharing
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralInitParameters.
func (in *GeneralInitParameters) DeepCopy() *GeneralInitParameters {
	if in == nil {
		return nil
	}
	out := new(GeneralInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralList) DeepCopyInto(out *GeneralList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]General, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralList.
func (in *GeneralList) DeepCopy() *GeneralList {
	if in == nil {
		return nil
	}
	out := new(GeneralList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GeneralList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralObservation) DeepCopyInto(out *GeneralObservation) {
	*out = *in
	if in.DefaultDashboardList != nil {
		in, out := &in.DefaultDashboardList, &out.DefaultDashboardList
		*out = make([]DefaultDashboardListObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnablePublicSharing != nil {
		in, out := &in.EnablePublicSharing, &out.EnablePublicSharing
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralObservation.
func (in *GeneralObservation) DeepCopy() *GeneralObservation {
	if in == nil {
		return nil
	}
	out := new(GeneralObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralParameters) DeepCopyInto(out *GeneralParameters) {
	*out = *in
	if in.DefaultDashboardList != nil {
		in, out := &in.DefaultDashboardList, &out.DefaultDashboardList
		*out = make([]DefaultDashboardListParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnablePublicSharing != nil {
		in, out := &in.EnablePublicSharing, &out.EnablePublicSharing
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralParameters.
func (in *GeneralParameters) DeepCopy() *GeneralParameters {
	if in == nil {
		return nil
	}
	out := new(GeneralParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralSpec) DeepCopyInto(out *GeneralSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralSpec.
func (in *GeneralSpec) DeepCopy() *GeneralSpec {
	if in == nil {
		return nil
	}
	out := new(GeneralSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralStatus) DeepCopyInto(out *GeneralStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralStatus.
func (in *GeneralStatus) DeepCopy() *GeneralStatus {
	if in == nil {
		return nil
	}
	out := new(GeneralStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Presets) DeepCopyInto(out *Presets) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Presets.
func (in *Presets) DeepCopy() *Presets {
	if in == nil {
		return nil
	}
	out := new(Presets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Presets) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetsInitParameters) DeepCopyInto(out *PresetsInitParameters) {
	*out = *in
	if in.DashboardPresetsList != nil {
		in, out := &in.DashboardPresetsList, &out.DashboardPresetsList
		*out = make([]DashboardPresetsListInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnableDashboardPresets != nil {
		in, out := &in.EnableDashboardPresets, &out.EnableDashboardPresets
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetsInitParameters.
func (in *PresetsInitParameters) DeepCopy() *PresetsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PresetsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetsList) DeepCopyInto(out *PresetsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Presets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetsList.
func (in *PresetsList) DeepCopy() *PresetsList {
	if in == nil {
		return nil
	}
	out := new(PresetsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PresetsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetsObservation) DeepCopyInto(out *PresetsObservation) {
	*out = *in
	if in.DashboardPresetsList != nil {
		in, out := &in.DashboardPresetsList, &out.DashboardPresetsList
		*out = make([]DashboardPresetsListObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnableDashboardPresets != nil {
		in, out := &in.EnableDashboardPresets, &out.EnableDashboardPresets
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetsObservation.
func (in *PresetsObservation) DeepCopy() *PresetsObservation {
	if in == nil {
		return nil
	}
	out := new(PresetsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetsParameters) DeepCopyInto(out *PresetsParameters) {
	*out = *in
	if in.DashboardPresetsList != nil {
		in, out := &in.DashboardPresetsList, &out.DashboardPresetsList
		*out = make([]DashboardPresetsListParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnableDashboardPresets != nil {
		in, out := &in.EnableDashboardPresets, &out.EnableDashboardPresets
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetsParameters.
func (in *PresetsParameters) DeepCopy() *PresetsParameters {
	if in == nil {
		return nil
	}
	out := new(PresetsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetsSpec) DeepCopyInto(out *PresetsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetsSpec.
func (in *PresetsSpec) DeepCopy() *PresetsSpec {
	if in == nil {
		return nil
	}
	out := new(PresetsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetsStatus) DeepCopyInto(out *PresetsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetsStatus.
func (in *PresetsStatus) DeepCopy() *PresetsStatus {
	if in == nil {
		return nil
	}
	out := new(PresetsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UrlpatternInitParameters) DeepCopyInto(out *UrlpatternInitParameters) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UrlpatternInitParameters.
func (in *UrlpatternInitParameters) DeepCopy() *UrlpatternInitParameters {
	if in == nil {
		return nil
	}
	out := new(UrlpatternInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UrlpatternObservation) DeepCopyInto(out *UrlpatternObservation) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UrlpatternObservation.
func (in *UrlpatternObservation) DeepCopy() *UrlpatternObservation {
	if in == nil {
		return nil
	}
	out := new(UrlpatternObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UrlpatternParameters) DeepCopyInto(out *UrlpatternParameters) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UrlpatternParameters.
func (in *UrlpatternParameters) DeepCopy() *UrlpatternParameters {
	if in == nil {
		return nil
	}
	out := new(UrlpatternParameters)
	in.DeepCopyInto(out)
	return out
}
