// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UpdatesInitParameters struct {

	// (Boolean) Automatic updates at earliest convenience
	// Automatic updates at earliest convenience
	AutoUpdate *bool `json:"autoUpdate,omitempty" tf:"auto_update,omitempty"`

	// (String) The scope of this setting (ENVIRONMENT_ACTIVE_GATE). Omit this property if you want to cover the whole environment.
	// The scope of this setting (ENVIRONMENT_ACTIVE_GATE). Omit this property if you want to cover the whole environment.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type UpdatesObservation struct {

	// (Boolean) Automatic updates at earliest convenience
	// Automatic updates at earliest convenience
	AutoUpdate *bool `json:"autoUpdate,omitempty" tf:"auto_update,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The scope of this setting (ENVIRONMENT_ACTIVE_GATE). Omit this property if you want to cover the whole environment.
	// The scope of this setting (ENVIRONMENT_ACTIVE_GATE). Omit this property if you want to cover the whole environment.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type UpdatesParameters struct {

	// (Boolean) Automatic updates at earliest convenience
	// Automatic updates at earliest convenience
	// +kubebuilder:validation:Optional
	AutoUpdate *bool `json:"autoUpdate,omitempty" tf:"auto_update,omitempty"`

	// (String) The scope of this setting (ENVIRONMENT_ACTIVE_GATE). Omit this property if you want to cover the whole environment.
	// The scope of this setting (ENVIRONMENT_ACTIVE_GATE). Omit this property if you want to cover the whole environment.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

// UpdatesSpec defines the desired state of Updates
type UpdatesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UpdatesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UpdatesInitParameters `json:"initProvider,omitempty"`
}

// UpdatesStatus defines the observed state of Updates.
type UpdatesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UpdatesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Updates is the Schema for the Updatess API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,dynatrace}
type Updates struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.autoUpdate) || (has(self.initProvider) && has(self.initProvider.autoUpdate))",message="spec.forProvider.autoUpdate is a required parameter"
	Spec   UpdatesSpec   `json:"spec"`
	Status UpdatesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UpdatesList contains a list of Updatess
type UpdatesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Updates `json:"items"`
}

// Repository type metadata.
var (
	Updates_Kind             = "Updates"
	Updates_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Updates_Kind}.String()
	Updates_KindAPIVersion   = Updates_Kind + "." + CRDGroupVersion.String()
	Updates_GroupVersionKind = CRDGroupVersion.WithKind(Updates_Kind)
)

func init() {
	SchemeBuilder.Register(&Updates{}, &UpdatesList{})
}
