// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AdvancedCorrelationInitParameters struct {

	// (String) Possible Values: CONTAINS, ENDS_WITH, EQUALS, STARTS_WITH
	// Possible Values: `CONTAINS`, `ENDS_WITH`, `EQUALS`, `STARTS_WITH`
	Matcher *string `json:"matcher,omitempty" tf:"matcher,omitempty"`

	// (String) Pattern
	// Pattern
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type AdvancedCorrelationObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Possible Values: CONTAINS, ENDS_WITH, EQUALS, STARTS_WITH
	// Possible Values: `CONTAINS`, `ENDS_WITH`, `EQUALS`, `STARTS_WITH`
	Matcher *string `json:"matcher,omitempty" tf:"matcher,omitempty"`

	// (String) Pattern
	// Pattern
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type AdvancedCorrelationParameters struct {

	// (String) Possible Values: CONTAINS, ENDS_WITH, EQUALS, STARTS_WITH
	// Possible Values: `CONTAINS`, `ENDS_WITH`, `EQUALS`, `STARTS_WITH`
	// +kubebuilder:validation:Optional
	Matcher *string `json:"matcher,omitempty" tf:"matcher,omitempty"`

	// (String) Pattern
	// Pattern
	// +kubebuilder:validation:Optional
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

// AdvancedCorrelationSpec defines the desired state of AdvancedCorrelation
type AdvancedCorrelationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AdvancedCorrelationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AdvancedCorrelationInitParameters `json:"initProvider,omitempty"`
}

// AdvancedCorrelationStatus defines the observed state of AdvancedCorrelation.
type AdvancedCorrelationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AdvancedCorrelationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AdvancedCorrelation is the Schema for the AdvancedCorrelations API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,dynatrace}
type AdvancedCorrelation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.matcher) || (has(self.initProvider) && has(self.initProvider.matcher))",message="spec.forProvider.matcher is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pattern) || (has(self.initProvider) && has(self.initProvider.pattern))",message="spec.forProvider.pattern is a required parameter"
	Spec   AdvancedCorrelationSpec   `json:"spec"`
	Status AdvancedCorrelationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdvancedCorrelationList contains a list of AdvancedCorrelations
type AdvancedCorrelationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdvancedCorrelation `json:"items"`
}

// Repository type metadata.
var (
	AdvancedCorrelation_Kind             = "AdvancedCorrelation"
	AdvancedCorrelation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdvancedCorrelation_Kind}.String()
	AdvancedCorrelation_KindAPIVersion   = AdvancedCorrelation_Kind + "." + CRDGroupVersion.String()
	AdvancedCorrelation_GroupVersionKind = CRDGroupVersion.WithKind(AdvancedCorrelation_Kind)
)

func init() {
	SchemeBuilder.Register(&AdvancedCorrelation{}, &AdvancedCorrelationList{})
}
