//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedEntitiesInitParameters) DeepCopyInto(out *AllowedEntitiesInitParameters) {
	*out = *in
	if in.Entity != nil {
		in, out := &in.Entity, &out.Entity
		*out = make([]EntityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedEntitiesInitParameters.
func (in *AllowedEntitiesInitParameters) DeepCopy() *AllowedEntitiesInitParameters {
	if in == nil {
		return nil
	}
	out := new(AllowedEntitiesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedEntitiesObservation) DeepCopyInto(out *AllowedEntitiesObservation) {
	*out = *in
	if in.Entity != nil {
		in, out := &in.Entity, &out.Entity
		*out = make([]EntityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedEntitiesObservation.
func (in *AllowedEntitiesObservation) DeepCopy() *AllowedEntitiesObservation {
	if in == nil {
		return nil
	}
	out := new(AllowedEntitiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedEntitiesParameters) DeepCopyInto(out *AllowedEntitiesParameters) {
	*out = *in
	if in.Entity != nil {
		in, out := &in.Entity, &out.Entity
		*out = make([]EntityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedEntitiesParameters.
func (in *AllowedEntitiesParameters) DeepCopy() *AllowedEntitiesParameters {
	if in == nil {
		return nil
	}
	out := new(AllowedEntitiesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialUsageSummaryInitParameters) DeepCopyInto(out *CredentialUsageSummaryInitParameters) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialUsageSummaryInitParameters.
func (in *CredentialUsageSummaryInitParameters) DeepCopy() *CredentialUsageSummaryInitParameters {
	if in == nil {
		return nil
	}
	out := new(CredentialUsageSummaryInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialUsageSummaryObservation) DeepCopyInto(out *CredentialUsageSummaryObservation) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialUsageSummaryObservation.
func (in *CredentialUsageSummaryObservation) DeepCopy() *CredentialUsageSummaryObservation {
	if in == nil {
		return nil
	}
	out := new(CredentialUsageSummaryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialUsageSummaryParameters) DeepCopyInto(out *CredentialUsageSummaryParameters) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialUsageSummaryParameters.
func (in *CredentialUsageSummaryParameters) DeepCopy() *CredentialUsageSummaryParameters {
	if in == nil {
		return nil
	}
	out := new(CredentialUsageSummaryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Credentials) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsInitParameters) DeepCopyInto(out *CredentialsInitParameters) {
	*out = *in
	if in.AllowContextlessRequests != nil {
		in, out := &in.AllowContextlessRequests, &out.AllowContextlessRequests
		*out = new(bool)
		**out = **in
	}
	if in.AllowedEntities != nil {
		in, out := &in.AllowedEntities, &out.AllowedEntities
		*out = make([]AllowedEntitiesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.CredentialUsageSummary != nil {
		in, out := &in.CredentialUsageSummary, &out.CredentialUsageSummary
		*out = make([]CredentialUsageSummaryInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = make([]ExternalInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerAccessOnly != nil {
		in, out := &in.OwnerAccessOnly, &out.OwnerAccessOnly
		*out = new(bool)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsInitParameters.
func (in *CredentialsInitParameters) DeepCopy() *CredentialsInitParameters {
	if in == nil {
		return nil
	}
	out := new(CredentialsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsList) DeepCopyInto(out *CredentialsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Credentials, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsList.
func (in *CredentialsList) DeepCopy() *CredentialsList {
	if in == nil {
		return nil
	}
	out := new(CredentialsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsObservation) DeepCopyInto(out *CredentialsObservation) {
	*out = *in
	if in.AllowContextlessRequests != nil {
		in, out := &in.AllowContextlessRequests, &out.AllowContextlessRequests
		*out = new(bool)
		**out = **in
	}
	if in.AllowedEntities != nil {
		in, out := &in.AllowedEntities, &out.AllowedEntities
		*out = make([]AllowedEntitiesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.CredentialUsageSummary != nil {
		in, out := &in.CredentialUsageSummary, &out.CredentialUsageSummary
		*out = make([]CredentialUsageSummaryObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = make([]ExternalObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerAccessOnly != nil {
		in, out := &in.OwnerAccessOnly, &out.OwnerAccessOnly
		*out = new(bool)
		**out = **in
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsObservation.
func (in *CredentialsObservation) DeepCopy() *CredentialsObservation {
	if in == nil {
		return nil
	}
	out := new(CredentialsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsParameters) DeepCopyInto(out *CredentialsParameters) {
	*out = *in
	if in.AllowContextlessRequests != nil {
		in, out := &in.AllowContextlessRequests, &out.AllowContextlessRequests
		*out = new(bool)
		**out = **in
	}
	if in.AllowedEntities != nil {
		in, out := &in.AllowedEntities, &out.AllowedEntities
		*out = make([]AllowedEntitiesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.CredentialUsageSummary != nil {
		in, out := &in.CredentialUsageSummary, &out.CredentialUsageSummary
		*out = make([]CredentialUsageSummaryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = make([]ExternalParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerAccessOnly != nil {
		in, out := &in.OwnerAccessOnly, &out.OwnerAccessOnly
		*out = new(bool)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsParameters.
func (in *CredentialsParameters) DeepCopy() *CredentialsParameters {
	if in == nil {
		return nil
	}
	out := new(CredentialsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSpec) DeepCopyInto(out *CredentialsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSpec.
func (in *CredentialsSpec) DeepCopy() *CredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsStatus) DeepCopyInto(out *CredentialsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsStatus.
func (in *CredentialsStatus) DeepCopy() *CredentialsStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityInitParameters) DeepCopyInto(out *EntityInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityInitParameters.
func (in *EntityInitParameters) DeepCopy() *EntityInitParameters {
	if in == nil {
		return nil
	}
	out := new(EntityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityObservation) DeepCopyInto(out *EntityObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityObservation.
func (in *EntityObservation) DeepCopy() *EntityObservation {
	if in == nil {
		return nil
	}
	out := new(EntityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityParameters) DeepCopyInto(out *EntityParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityParameters.
func (in *EntityParameters) DeepCopy() *EntityParameters {
	if in == nil {
		return nil
	}
	out := new(EntityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalInitParameters) DeepCopyInto(out *ExternalInitParameters) {
	*out = *in
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
	if in.Clientid != nil {
		in, out := &in.Clientid, &out.Clientid
		*out = new(string)
		**out = **in
	}
	if in.CredentialsUsedForExternalSynchronization != nil {
		in, out := &in.CredentialsUsedForExternalSynchronization, &out.CredentialsUsedForExternalSynchronization
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FolderName != nil {
		in, out := &in.FolderName, &out.FolderName
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.PathToCredentials != nil {
		in, out := &in.PathToCredentials, &out.PathToCredentials
		*out = new(string)
		**out = **in
	}
	if in.Roleid != nil {
		in, out := &in.Roleid, &out.Roleid
		*out = new(string)
		**out = **in
	}
	if in.SafeName != nil {
		in, out := &in.SafeName, &out.SafeName
		*out = new(string)
		**out = **in
	}
	if in.Secretid != nil {
		in, out := &in.Secretid, &out.Secretid
		*out = new(string)
		**out = **in
	}
	if in.Tenantid != nil {
		in, out := &in.Tenantid, &out.Tenantid
		*out = new(string)
		**out = **in
	}
	if in.TokenSecretName != nil {
		in, out := &in.TokenSecretName, &out.TokenSecretName
		*out = new(string)
		**out = **in
	}
	if in.UsernamePasswordForCpm != nil {
		in, out := &in.UsernamePasswordForCpm, &out.UsernamePasswordForCpm
		*out = new(string)
		**out = **in
	}
	if in.UsernameSecretName != nil {
		in, out := &in.UsernameSecretName, &out.UsernameSecretName
		*out = new(string)
		**out = **in
	}
	if in.VaultNamespace != nil {
		in, out := &in.VaultNamespace, &out.VaultNamespace
		*out = new(string)
		**out = **in
	}
	if in.VaultURL != nil {
		in, out := &in.VaultURL, &out.VaultURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalInitParameters.
func (in *ExternalInitParameters) DeepCopy() *ExternalInitParameters {
	if in == nil {
		return nil
	}
	out := new(ExternalInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalObservation) DeepCopyInto(out *ExternalObservation) {
	*out = *in
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
	if in.Clientid != nil {
		in, out := &in.Clientid, &out.Clientid
		*out = new(string)
		**out = **in
	}
	if in.CredentialsUsedForExternalSynchronization != nil {
		in, out := &in.CredentialsUsedForExternalSynchronization, &out.CredentialsUsedForExternalSynchronization
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FolderName != nil {
		in, out := &in.FolderName, &out.FolderName
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.PathToCredentials != nil {
		in, out := &in.PathToCredentials, &out.PathToCredentials
		*out = new(string)
		**out = **in
	}
	if in.Roleid != nil {
		in, out := &in.Roleid, &out.Roleid
		*out = new(string)
		**out = **in
	}
	if in.SafeName != nil {
		in, out := &in.SafeName, &out.SafeName
		*out = new(string)
		**out = **in
	}
	if in.Secretid != nil {
		in, out := &in.Secretid, &out.Secretid
		*out = new(string)
		**out = **in
	}
	if in.Tenantid != nil {
		in, out := &in.Tenantid, &out.Tenantid
		*out = new(string)
		**out = **in
	}
	if in.TokenSecretName != nil {
		in, out := &in.TokenSecretName, &out.TokenSecretName
		*out = new(string)
		**out = **in
	}
	if in.UsernamePasswordForCpm != nil {
		in, out := &in.UsernamePasswordForCpm, &out.UsernamePasswordForCpm
		*out = new(string)
		**out = **in
	}
	if in.UsernameSecretName != nil {
		in, out := &in.UsernameSecretName, &out.UsernameSecretName
		*out = new(string)
		**out = **in
	}
	if in.VaultNamespace != nil {
		in, out := &in.VaultNamespace, &out.VaultNamespace
		*out = new(string)
		**out = **in
	}
	if in.VaultURL != nil {
		in, out := &in.VaultURL, &out.VaultURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalObservation.
func (in *ExternalObservation) DeepCopy() *ExternalObservation {
	if in == nil {
		return nil
	}
	out := new(ExternalObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalParameters) DeepCopyInto(out *ExternalParameters) {
	*out = *in
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
	if in.Clientid != nil {
		in, out := &in.Clientid, &out.Clientid
		*out = new(string)
		**out = **in
	}
	if in.CredentialsUsedForExternalSynchronization != nil {
		in, out := &in.CredentialsUsedForExternalSynchronization, &out.CredentialsUsedForExternalSynchronization
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FolderName != nil {
		in, out := &in.FolderName, &out.FolderName
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretName != nil {
		in, out := &in.PasswordSecretName, &out.PasswordSecretName
		*out = new(string)
		**out = **in
	}
	if in.PathToCredentials != nil {
		in, out := &in.PathToCredentials, &out.PathToCredentials
		*out = new(string)
		**out = **in
	}
	if in.Roleid != nil {
		in, out := &in.Roleid, &out.Roleid
		*out = new(string)
		**out = **in
	}
	if in.SafeName != nil {
		in, out := &in.SafeName, &out.SafeName
		*out = new(string)
		**out = **in
	}
	if in.Secretid != nil {
		in, out := &in.Secretid, &out.Secretid
		*out = new(string)
		**out = **in
	}
	if in.Tenantid != nil {
		in, out := &in.Tenantid, &out.Tenantid
		*out = new(string)
		**out = **in
	}
	if in.TokenSecretName != nil {
		in, out := &in.TokenSecretName, &out.TokenSecretName
		*out = new(string)
		**out = **in
	}
	if in.UsernamePasswordForCpm != nil {
		in, out := &in.UsernamePasswordForCpm, &out.UsernamePasswordForCpm
		*out = new(string)
		**out = **in
	}
	if in.UsernameSecretName != nil {
		in, out := &in.UsernameSecretName, &out.UsernameSecretName
		*out = new(string)
		**out = **in
	}
	if in.VaultNamespace != nil {
		in, out := &in.VaultNamespace, &out.VaultNamespace
		*out = new(string)
		**out = **in
	}
	if in.VaultURL != nil {
		in, out := &in.VaultURL, &out.VaultURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalParameters.
func (in *ExternalParameters) DeepCopy() *ExternalParameters {
	if in == nil {
		return nil
	}
	out := new(ExternalParameters)
	in.DeepCopyInto(out)
	return out
}
