// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Availability) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupDetection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupDetectionFlags) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupMonitoring) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupRum) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupSimpleDetection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Monitoring) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MonitoringRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Visibility) Hub() {}
