// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type EventPatternInitParameters struct {

	// (Boolean) Activate
	// Activate
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) Field selector name
	// Field selector name
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) The set of allowed characters for this field has been extended with ActiveGate version 1.259. For more details, see the documentation.
	// The set of allowed characters for this field has been extended with ActiveGate version 1.259. For more details, see the [documentation](https://dt-url.net/7h23wuk#set-up-event-field-selectors).
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type EventPatternObservation struct {

	// (Boolean) Activate
	// Activate
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) Field selector name
	// Field selector name
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) The set of allowed characters for this field has been extended with ActiveGate version 1.259. For more details, see the documentation.
	// The set of allowed characters for this field has been extended with ActiveGate version 1.259. For more details, see the [documentation](https://dt-url.net/7h23wuk#set-up-event-field-selectors).
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type EventPatternParameters struct {

	// (Boolean) Activate
	// Activate
	// +kubebuilder:validation:Optional
	Active *bool `json:"active" tf:"active,omitempty"`

	// (String) Field selector name
	// Field selector name
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// (String) The set of allowed characters for this field has been extended with ActiveGate version 1.259. For more details, see the documentation.
	// The set of allowed characters for this field has been extended with ActiveGate version 1.259. For more details, see the [documentation](https://dt-url.net/7h23wuk#set-up-event-field-selectors).
	// +kubebuilder:validation:Optional
	Pattern *string `json:"pattern" tf:"pattern,omitempty"`
}

type EventPatternsInitParameters struct {

	// (Block List, Min: 1) (see below for nested schema)
	EventPattern []EventPatternInitParameters `json:"eventPattern,omitempty" tf:"event_pattern,omitempty"`
}

type EventPatternsObservation struct {

	// (Block List, Min: 1) (see below for nested schema)
	EventPattern []EventPatternObservation `json:"eventPattern,omitempty" tf:"event_pattern,omitempty"`
}

type EventPatternsParameters struct {

	// (Block List, Min: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	EventPattern []EventPatternParameters `json:"eventPattern" tf:"event_pattern,omitempty"`
}

type MonitoringInitParameters struct {

	// (Boolean) Monitor Kubernetes namespaces, services, workloads, and pods
	// Monitor Kubernetes namespaces, services, workloads, and pods
	CloudApplicationPipelineEnabled *bool `json:"cloudApplicationPipelineEnabled,omitempty" tf:"cloud_application_pipeline_enabled,omitempty"`

	// (Block List, Max: 1) Define Kubernetes event filters to ingest events into your environment. For more details, see the documentation. (see below for nested schema)
	// Define Kubernetes event filters to ingest events into your environment. For more details, see the [documentation](https://dt-url.net/2201p0u).
	EventPatterns []EventPatternsInitParameters `json:"eventPatterns,omitempty" tf:"event_patterns,omitempty"`

	// (Boolean) All events are monitored unless event filters are specified. All ingested events are subject to licensing by default.
	// All events are monitored unless event filters are specified. All ingested events are subject to licensing by default.
	//
	// If you have a DPS license see [licensing documentation](https://dt-url.net/cee34zj) for details.
	//
	// If you have a non-DPS license see [DDUs for events](https://dt-url.net/5n03vcu) for details.
	EventProcessingActive *bool `json:"eventProcessingActive,omitempty" tf:"event_processing_active,omitempty"`

	// (Boolean) Include only events specified by Events Field Selectors
	// Include only events specified by Events Field Selectors
	FilterEvents *bool `json:"filterEvents,omitempty" tf:"filter_events,omitempty"`

	// (Boolean) For a list of included events, see the documentation.
	// For a list of included events, see the [documentation](https://dt-url.net/l61d02no).
	IncludeAllFdiEvents *bool `json:"includeAllFdiEvents,omitempty" tf:"include_all_fdi_events,omitempty"`

	// (Boolean) Workload and node resource metrics are based on a subset of cAdvisor metrics. Depending on your Kubernetes cluster size, this may increase the CPU/memory resource consumption of your ActiveGate.
	// Workload and node resource metrics are based on a subset of cAdvisor metrics. Depending on your Kubernetes cluster size, this may increase the CPU/memory resource consumption of your ActiveGate.
	OpenMetricsBuiltinEnabled *bool `json:"openMetricsBuiltinEnabled,omitempty" tf:"open_metrics_builtin_enabled,omitempty"`

	// (Boolean) For annotation guidance, see the documentation.
	// For annotation guidance, see the [documentation](https://dt-url.net/g42i0ppw).
	OpenMetricsPipelineEnabled *bool `json:"openMetricsPipelineEnabled,omitempty" tf:"open_metrics_pipeline_enabled,omitempty"`

	// (Boolean, Deprecated) To enable dashboards and alerts, add the Kubernetes persistent volume claims extension to your environment.
	// To enable dashboards and alerts, add the [Kubernetes persistent volume claims](ui/hub/ext/com.dynatrace.extension.kubernetes-pvc) extension to your environment.
	PvcMonitoringEnabled *bool `json:"pvcMonitoringEnabled,omitempty" tf:"pvc_monitoring_enabled,omitempty"`

	// (String) The scope of this setting (KUBERNETES_CLUSTER). Omit this property if you want to cover the whole environment.
	// The scope of this setting (KUBERNETES_CLUSTER). Omit this property if you want to cover the whole environment.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type MonitoringObservation struct {

	// (Boolean) Monitor Kubernetes namespaces, services, workloads, and pods
	// Monitor Kubernetes namespaces, services, workloads, and pods
	CloudApplicationPipelineEnabled *bool `json:"cloudApplicationPipelineEnabled,omitempty" tf:"cloud_application_pipeline_enabled,omitempty"`

	// (Block List, Max: 1) Define Kubernetes event filters to ingest events into your environment. For more details, see the documentation. (see below for nested schema)
	// Define Kubernetes event filters to ingest events into your environment. For more details, see the [documentation](https://dt-url.net/2201p0u).
	EventPatterns []EventPatternsObservation `json:"eventPatterns,omitempty" tf:"event_patterns,omitempty"`

	// (Boolean) All events are monitored unless event filters are specified. All ingested events are subject to licensing by default.
	// All events are monitored unless event filters are specified. All ingested events are subject to licensing by default.
	//
	// If you have a DPS license see [licensing documentation](https://dt-url.net/cee34zj) for details.
	//
	// If you have a non-DPS license see [DDUs for events](https://dt-url.net/5n03vcu) for details.
	EventProcessingActive *bool `json:"eventProcessingActive,omitempty" tf:"event_processing_active,omitempty"`

	// (Boolean) Include only events specified by Events Field Selectors
	// Include only events specified by Events Field Selectors
	FilterEvents *bool `json:"filterEvents,omitempty" tf:"filter_events,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) For a list of included events, see the documentation.
	// For a list of included events, see the [documentation](https://dt-url.net/l61d02no).
	IncludeAllFdiEvents *bool `json:"includeAllFdiEvents,omitempty" tf:"include_all_fdi_events,omitempty"`

	// (Boolean) Workload and node resource metrics are based on a subset of cAdvisor metrics. Depending on your Kubernetes cluster size, this may increase the CPU/memory resource consumption of your ActiveGate.
	// Workload and node resource metrics are based on a subset of cAdvisor metrics. Depending on your Kubernetes cluster size, this may increase the CPU/memory resource consumption of your ActiveGate.
	OpenMetricsBuiltinEnabled *bool `json:"openMetricsBuiltinEnabled,omitempty" tf:"open_metrics_builtin_enabled,omitempty"`

	// (Boolean) For annotation guidance, see the documentation.
	// For annotation guidance, see the [documentation](https://dt-url.net/g42i0ppw).
	OpenMetricsPipelineEnabled *bool `json:"openMetricsPipelineEnabled,omitempty" tf:"open_metrics_pipeline_enabled,omitempty"`

	// (Boolean, Deprecated) To enable dashboards and alerts, add the Kubernetes persistent volume claims extension to your environment.
	// To enable dashboards and alerts, add the [Kubernetes persistent volume claims](ui/hub/ext/com.dynatrace.extension.kubernetes-pvc) extension to your environment.
	PvcMonitoringEnabled *bool `json:"pvcMonitoringEnabled,omitempty" tf:"pvc_monitoring_enabled,omitempty"`

	// (String) The scope of this setting (KUBERNETES_CLUSTER). Omit this property if you want to cover the whole environment.
	// The scope of this setting (KUBERNETES_CLUSTER). Omit this property if you want to cover the whole environment.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type MonitoringParameters struct {

	// (Boolean) Monitor Kubernetes namespaces, services, workloads, and pods
	// Monitor Kubernetes namespaces, services, workloads, and pods
	// +kubebuilder:validation:Optional
	CloudApplicationPipelineEnabled *bool `json:"cloudApplicationPipelineEnabled,omitempty" tf:"cloud_application_pipeline_enabled,omitempty"`

	// (Block List, Max: 1) Define Kubernetes event filters to ingest events into your environment. For more details, see the documentation. (see below for nested schema)
	// Define Kubernetes event filters to ingest events into your environment. For more details, see the [documentation](https://dt-url.net/2201p0u).
	// +kubebuilder:validation:Optional
	EventPatterns []EventPatternsParameters `json:"eventPatterns,omitempty" tf:"event_patterns,omitempty"`

	// (Boolean) All events are monitored unless event filters are specified. All ingested events are subject to licensing by default.
	// All events are monitored unless event filters are specified. All ingested events are subject to licensing by default.
	//
	// If you have a DPS license see [licensing documentation](https://dt-url.net/cee34zj) for details.
	//
	// If you have a non-DPS license see [DDUs for events](https://dt-url.net/5n03vcu) for details.
	// +kubebuilder:validation:Optional
	EventProcessingActive *bool `json:"eventProcessingActive,omitempty" tf:"event_processing_active,omitempty"`

	// (Boolean) Include only events specified by Events Field Selectors
	// Include only events specified by Events Field Selectors
	// +kubebuilder:validation:Optional
	FilterEvents *bool `json:"filterEvents,omitempty" tf:"filter_events,omitempty"`

	// (Boolean) For a list of included events, see the documentation.
	// For a list of included events, see the [documentation](https://dt-url.net/l61d02no).
	// +kubebuilder:validation:Optional
	IncludeAllFdiEvents *bool `json:"includeAllFdiEvents,omitempty" tf:"include_all_fdi_events,omitempty"`

	// (Boolean) Workload and node resource metrics are based on a subset of cAdvisor metrics. Depending on your Kubernetes cluster size, this may increase the CPU/memory resource consumption of your ActiveGate.
	// Workload and node resource metrics are based on a subset of cAdvisor metrics. Depending on your Kubernetes cluster size, this may increase the CPU/memory resource consumption of your ActiveGate.
	// +kubebuilder:validation:Optional
	OpenMetricsBuiltinEnabled *bool `json:"openMetricsBuiltinEnabled,omitempty" tf:"open_metrics_builtin_enabled,omitempty"`

	// (Boolean) For annotation guidance, see the documentation.
	// For annotation guidance, see the [documentation](https://dt-url.net/g42i0ppw).
	// +kubebuilder:validation:Optional
	OpenMetricsPipelineEnabled *bool `json:"openMetricsPipelineEnabled,omitempty" tf:"open_metrics_pipeline_enabled,omitempty"`

	// (Boolean, Deprecated) To enable dashboards and alerts, add the Kubernetes persistent volume claims extension to your environment.
	// To enable dashboards and alerts, add the [Kubernetes persistent volume claims](ui/hub/ext/com.dynatrace.extension.kubernetes-pvc) extension to your environment.
	// +kubebuilder:validation:Optional
	PvcMonitoringEnabled *bool `json:"pvcMonitoringEnabled,omitempty" tf:"pvc_monitoring_enabled,omitempty"`

	// (String) The scope of this setting (KUBERNETES_CLUSTER). Omit this property if you want to cover the whole environment.
	// The scope of this setting (KUBERNETES_CLUSTER). Omit this property if you want to cover the whole environment.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

// MonitoringSpec defines the desired state of Monitoring
type MonitoringSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MonitoringParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MonitoringInitParameters `json:"initProvider,omitempty"`
}

// MonitoringStatus defines the observed state of Monitoring.
type MonitoringStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MonitoringObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Monitoring is the Schema for the Monitorings API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,dynatrace}
type Monitoring struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudApplicationPipelineEnabled) || (has(self.initProvider) && has(self.initProvider.cloudApplicationPipelineEnabled))",message="spec.forProvider.cloudApplicationPipelineEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.eventProcessingActive) || (has(self.initProvider) && has(self.initProvider.eventProcessingActive))",message="spec.forProvider.eventProcessingActive is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.openMetricsBuiltinEnabled) || (has(self.initProvider) && has(self.initProvider.openMetricsBuiltinEnabled))",message="spec.forProvider.openMetricsBuiltinEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.openMetricsPipelineEnabled) || (has(self.initProvider) && has(self.initProvider.openMetricsPipelineEnabled))",message="spec.forProvider.openMetricsPipelineEnabled is a required parameter"
	Spec   MonitoringSpec   `json:"spec"`
	Status MonitoringStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MonitoringList contains a list of Monitorings
type MonitoringList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Monitoring `json:"items"`
}

// Repository type metadata.
var (
	Monitoring_Kind             = "Monitoring"
	Monitoring_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Monitoring_Kind}.String()
	Monitoring_KindAPIVersion   = Monitoring_Kind + "." + CRDGroupVersion.String()
	Monitoring_GroupVersionKind = CRDGroupVersion.WithKind(Monitoring_Kind)
)

func init() {
	SchemeBuilder.Register(&Monitoring{}, &MonitoringList{})
}
