// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AppAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppAutoInjection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppBeaconEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppBeaconOrigins) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppCustomConfigProperties) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppCustomErrors) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppCustomInjection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppCustomPropRestrictions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppEnablement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppInjectionCookie) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppIPAddressExclusion) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppJavascriptFilename) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppJavascriptUpdates) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppJavascriptVersion) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppKeyPerformanceCustom) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppKeyPerformanceLoad) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppKeyPerformanceXhr) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Application) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppManualInsertion) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppRequestErrors) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppResourceCleanup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AppResourceTypes) Hub() {}
