// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ExtensionV2ConfigInitParameters struct {

	// liberty-cp.
	// The fully qualified name of the extension, such as `com.dynatrace.extension.jmx-liberty-cp`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The scope this monitoring configuration will be defined for
	// The scope this monitoring configuration will be defined for
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) The JSON encoded value for this monitoring configuration
	// The JSON encoded value for this monitoring configuration
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ExtensionV2ConfigObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// liberty-cp.
	// The fully qualified name of the extension, such as `com.dynatrace.extension.jmx-liberty-cp`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The scope this monitoring configuration will be defined for
	// The scope this monitoring configuration will be defined for
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) The JSON encoded value for this monitoring configuration
	// The JSON encoded value for this monitoring configuration
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ExtensionV2ConfigParameters struct {

	// liberty-cp.
	// The fully qualified name of the extension, such as `com.dynatrace.extension.jmx-liberty-cp`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The scope this monitoring configuration will be defined for
	// The scope this monitoring configuration will be defined for
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) The JSON encoded value for this monitoring configuration
	// The JSON encoded value for this monitoring configuration
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// ExtensionV2ConfigSpec defines the desired state of ExtensionV2Config
type ExtensionV2ConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ExtensionV2ConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExtensionV2ConfigInitParameters `json:"initProvider,omitempty"`
}

// ExtensionV2ConfigStatus defines the observed state of ExtensionV2Config.
type ExtensionV2ConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExtensionV2ConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ExtensionV2Config is the Schema for the ExtensionV2Configs API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type ExtensionV2Config struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scope) || (has(self.initProvider) && has(self.initProvider.scope))",message="spec.forProvider.scope is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   ExtensionV2ConfigSpec   `json:"spec"`
	Status ExtensionV2ConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExtensionV2ConfigList contains a list of ExtensionV2Configs
type ExtensionV2ConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExtensionV2Config `json:"items"`
}

// Repository type metadata.
var (
	ExtensionV2Config_Kind             = "ExtensionV2Config"
	ExtensionV2Config_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ExtensionV2Config_Kind}.String()
	ExtensionV2Config_KindAPIVersion   = ExtensionV2Config_Kind + "." + CRDGroupVersion.String()
	ExtensionV2Config_GroupVersionKind = CRDGroupVersion.WithKind(ExtensionV2Config_Kind)
)

func init() {
	SchemeBuilder.Register(&ExtensionV2Config{}, &ExtensionV2ConfigList{})
}
